### ISSUE TITLE
401 Unauthorized

### ISSUE THREAD

**Issue by csjjpm** [plexinc/roku-client-public#309]
Hi,
  I've just installed the plexclassic 3.1.5 on a new NowTV version 2 (black one).  I am away from home and try to add my server I get a 401 Unauthorized error.  I can access the server from a browser and my phone and tablet but not from my NowTV box.
  From the laptop I have to append :32400/web but it seems the NowTV channel isn't doing this.
Paul

**Comment by ljunkie** [comment]
You can't add a manual IP if you are using Plex Home or PIN, which is why you'd get a 401, unauthorized error. 

You will have to either remove your PIN (if you are not using Plex Home), or sign into the client and server with your Plex Account and it will auto discover the server without the need to manually enter your IP address.

**Comment by csjjpm** [comment]
Duh! Of course.  That is what I did ages ago the first time on an old NowTV box.... sorry for wasting you time and thank you for the quick response.

**Comment by ljunkie** [comment]
no worries, glad it was _easy_! enjoy! :)
